#!/bin/bash
#*******************************************************************************
# Version 1.0
# COPYRIGHT Ericsson 2022
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#********************************************************************************
#
# DO NOT EDIT This file if found on a cENM service group project.
# Master file is under: https://gerrit.ericsson.se/gitweb?p=OSS/ENM-Parent/SQ-Gate/com.ericsson.oss.containerisation/ucit-cENM.git
#
# This file is updated by run_update_credm_info script
# see: https://confluence-oss.seli.wh.rnd.internal.ericsson.com/display/ENMCOMECIM/Script+automation+for+Credential+Manager+introduction+on+cENM+service+group
#
# Last revision: 2023-12-01
#
if [ -d /var/tmp ]; then
  LOG_DIR=/var/tmp
else
  LOG_DIR=/tmp
fi
LOG=$LOG_DIR/updateCertificatesLinks.log

touch $LOG

my_logger() {
  d=$(date)
  echo "$d $1" | tee -a $LOG
}
#
readonly dt=$(date +%s)
#
readonly script_name=$0
readonly release=$(grep '^# Last revision:' $script_name | sed 's/^# Last revision://')
readonly version=$(grep '^# Version' $script_name | sed 's/^# Version//')
if grep -q "Starting" $LOG /dev/null 2>/dev/null ; then
  if grep -q "Last run" $LOG ; then
    sed -i "s/.*Last run/$dt Last run/" $LOG
  else
    my_logger "Last run"
  fi
else
  my_logger "Starting $script_name release: $release version: $version"
fi
#
runscript_list=""
#
run_script() {
  cert=$1
  certRun=$(dirname $cert)/.$(basename $cert).run
  if [ -f $cert ]; then
    for rs in $runscript_list
    do
      my_logger "Processing $rs entry"
      local c=$(echo "$rs" | sed 's/:.*//')
      local si=$(echo "$rs" | sed 's/.*://')
      if [ "$c" == "$cert" ]; then
        s=$(echo "$si" | sed 's/_-_.*//')
        s_cmd=$(echo "$si" | sed 's/_-_/ /g')
        if [ -f $s ]; then
          if [ ! -f $certRun ]; then
            touch $certRun
          fi
          if grep -q "running $s at time $dt" $LOG; then
            my_logger "skipping $s because already run at time $dt"
          else
            my_logger "running $s at time $dt"
            chmod a+x $s
            $s_cmd
          fi
        fi
      fi
    done
  fi
  if grep -q "$s" $certRun ; then
    sed -i "s,.*$s,$dt $s," $certRun
  else
    echo "$dt $s" >> $certRun
  fi
}
#
#
DEFAULT_TLS_MOUNT_PATH='/ericsson/credm/tlsMount'
if [ -z "$TLS_MOUNT_PATH" ]; then
  if ! grep -q "TLS_MOUNT_PATH not defined" $LOG ; then
    my_logger "TLS_MOUNT_PATH not defined, using default value: $DEFAULT_TLS_MOUNT_PATH"
  fi
  TLS_MOUNT_PATH="$DEFAULT_TLS_MOUNT_PATH"
fi
#
# from deployment.yaml
readonly TLS_DIR=$TLS_MOUNT_PATH
readonly TLS_LOCATION=tlsStoreLocation
readonly TLS_DATA=tlsStoreData

# Update links to keystores
d=$(date)

for  _secret_mount_ in ${TLS_DIR}/*
do
    if [ -d ${_secret_mount_} ]
    then
      tlsFilename=$(cat ${_secret_mount_}/${TLS_LOCATION})
      cksumDir=$(dirname $tlsFilename)
      cksumFile=$cksumDir/.$(basename $tlsFilename).cksum
      if [ ! -f ${tlsFilename} ]; then
        my_logger "MAKE MISSING LINK ${tlsFilename}"
        ln -s ${_secret_mount_}/${TLS_DATA} ${tlsFilename}
      fi
      csum=$(cksum $tlsFilename | sed 's/ .*//')
      if [ -f $cksumFile ]; then
        if grep -q "^Checksum:" $cksumFile ; then
          csum_old=$(grep "^Checksum:" $cksumFile | sed 's/Checksum://')
          if [ "$csum" != "$csum_old" ]; then
            my_logger "RENEW LINK ${tlsFilename}"
            touch -h ${tlsFilename}
            my_logger "UPDATING CKSUM LINE ON $cksumFile"
            sed -i "s/^Checksum:.*/Checksum:$csum/" $cksumFile
            run_script ${tlsFilename}
          fi
        else
          my_logger "ADDING CKSUM LINE ON $cksumFile"
          echo "" >> $cksumFile
          sed -i "1 i Checksum:$csum" $cksumFile
        fi
      else
        my_logger "CREATING CKSUM FILE $cksumFile"
        echo "Checksum:$csum" > $cksumFile
      fi
    fi
done

exit 0
